image: "python:3.10"

stages:
  - test

before_script:
  - apt update -y
  - apt upgrade -y
  - pip3 install tox

test:
  stage: test
  script:
    - tox
  artifacts:
    name: TRANSFORMER-$CI_PIPELINE_ID
    paths:
      - htmlcov
    # untracked: false

    expire_in: 30 days
    # public: true
