version: '3.4'

services:
  app:
    image: app_tcc
    container_name: app_tcc
    command: 'tail -f /dev/null'
    user: python
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      -  ENVIROMENT:develop
    volumes:
      - ".:/home/python/app/"
      - "./images:/tmp/tcc/"
