# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Creating requirements.txt
      run: echo flake8 >> requirements.txt

    - name: Set up Python 3.10.5
      uses: actions/setup-python@v3
      id: setup-python
      with:
        python-version: "3.10.5"
        cache: pip

    - name: Run lint
      run: |
        pip install flake8
        make lint

  docker-build:
    runs-on: ubuntu-latest
    name: Docker Image Build
    needs:
      - lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2

        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_tcc:test
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app_tcc:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app_tcc:buildcache,mode=max

  tests:
    runs-on: ubuntu-latest
    name: Test using docker container
    needs:
      - docker-build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Test using docker container
        run: |
          docker run --entrypoint ".docker/entrypoint/test.sh"  ${{ secrets.DOCKERHUB_USERNAME }}/app_tcc:test
